### ISSUE TITLE
move all relevant config files to `docker` folder and update docker data accordingly

### ISSUE THREAD

**Issue by yactouat** [yactouat/core_PHP_CRUD_app#26]

**Comment by DipayanP007** [comment]
Hey @yactouat I can work on this. I just need to move the docker-compose file to docker folder and make necessary changes right?

**Comment by DipayanP007** [comment]
Hey @yactouat I made the changes kindly review them

**Comment by yactouat** [comment]
hey @DipayanP007 it's merged, thank you very much :) this helps !
